"use server";

import { Report } from "@/types/reports";

export const testReports: Report[] = [
  {
    id: "1",
    firstName: "Alice",
    lastName: "Johnson",
    event: "Football",
    type: "Respect",
    description: "Helped an injured opponent.",
    country: "Cameroon",
    gender: "female",
    age: 24,
    date: "2025-07-05",
  },
  {
    id: "2",
    firstName: "John",
    lastName: "Doe",
    event: "Basketball",
    type: "Altruisme",
    description: "Gave up a winning shot to assist a teammate.",
    country: "Cameroon",
    gender: "male",
    age: 29,
    date: "2025-07-04",
  },
  {
    id: "3",
    firstName: "Marie",
    lastName: "Claire",
    event: "Volleyball",
    type: "Courage",
    description: "Played through injury to support her team.",
    country: "Senegal",
    gender: "female",
    age: 21,
    date: "2025-07-03",
  },
  {
    id: "4",
    firstName: "Joseph",
    lastName: "Ngoma",
    event: "Rugby",
    type: "Honnêteté",
    description: "Admitted a foul the referee didn’t see.",
    country: "Nigeria",
    gender: "male",
    age: 27,
    date: "2025-07-02",
  },
  {
    id: "5",
    firstName: "Fatima",
    lastName: "Ali",
    event: "Cyclisme",
    type: "Respect",
    description: "Waited for a fellow cyclist who had a flat tire.",
    country: "Mali",
    gender: "female",
    age: 23,
    date: "2025-07-01",
  },
  {
    id: "6",
    firstName: "Pierre",
    lastName: "Tchouameni",
    event: "Football",
    type: "Altruisme",
    description: "Helped a teammate overcome anxiety before a match.",
    country: "Cameroon",
    gender: "male",
    age: 26,
    date: "2025-06-30",
  },
  {
    id: "7",
    firstName: "Léa",
    lastName: "Mbi",
    event: "Athlétisme",
    type: "Courage",
    description: "Finished a marathon despite collapsing twice.",
    country: "Ivory Coast",
    gender: "female",
    age: 30,
    date: "2025-06-29",
  },
  {
    id: "8",
    firstName: "Eric",
    lastName: "Bakary",
    event: "Handball",
    type: "Honnêteté",
    description: "Returned a wrongly awarded point.",
    country: "Gabon",
    gender: "male",
    age: 22,
    date: "2025-06-28",
  },
  {
    id: "9",
    firstName: "Diane",
    lastName: "Kouassi",
    event: "Natation",
    type: "Respect",
    description: "Congratulated every opponent personally.",
    country: "Cameroon",
    gender: "female",
    age: 19,
    date: "2025-06-27",
  },
  {
    id: "10",
    firstName: "Samuel",
    lastName: "Etame",
    event: "Tennis",
    type: "Altruisme",
    description: "Offered coaching tips to a new competitor.",
    country: "Cameroon",
    gender: "male",
    age: 33,
    date: "2025-06-26",
  },
  {
    id: "11",
    firstName: "Olivia",
    lastName: "Nseke",
    event: "Football",
    type: "Respect",
    description: "Stopped play when an opponent fainted.",
    country: "Chad",
    gender: "female",
    age: 25,
    date: "2025-06-25",
  },
  {
    id: "12",
    firstName: "Michael",
    lastName: "Youssouf",
    event: "Basketball",
    type: "Courage",
    description: "Returned to the game after injury to inspire team.",
    country: "Cameroon",
    gender: "male",
    age: 31,
    date: "2025-06-24",
  },
  {
    id: "13",
    firstName: "Grace",
    lastName: "Mboua",
    event: "Cyclisme",
    type: "Honnêteté",
    description: "Reported her own technical violation.",
    country: "Togo",
    gender: "female",
    age: 28,
    date: "2025-06-23",
  },
  {
    id: "14",
    firstName: "Nicolas",
    lastName: "Fonkoua",
    event: "Handball",
    type: "Respect",
    description: "Apologized after accidental foul play.",
    country: "Cameroon",
    gender: "male",
    age: 20,
    date: "2025-06-22",
  },
  {
    id: "15",
    firstName: "Sarah",
    lastName: "Ndong",
    event: "Athlétisme",
    type: "Altruisme",
    description: "Helped a rival runner finish the race.",
    country: "Benin",
    gender: "female",
    age: 32,
    date: "2025-06-21",
  },
];

export async function getReports(): Promise<Report[]> {
  return new Promise((resolve) => setTimeout(() => resolve(testReports), 1000));
}
